frontend:
  image: konradkleine/docker-registry-frontend:v2
  links:
    - proxy
  ports:
    - 8443:80
  restart: always
  #volumes:
    #- ./frontend/certs/frontend.crt:/etc/apache2/server.crt:ro
    #- ./frontend/certs/frontend.key:/etc/apache2/server.key:ro
  environment:
    # The front-end is SSL protected
    #- ENV_USE_SSL=yes
    - ENV_DOCKER_REGISTRY_HOST=proxy
    - ENV_DOCKER_REGISTRY_PORT=5000
    # The registry is SSL protected as well
    #- ENV_DOCKER_REGISTRY_USE_SSL=1

registry:
  container_name: registry
  image: registry:2
  restart: always
  #volumes:
    # Mount the config directory
    #- ./registry/config:/etc/docker/registry:ro
    # Make the registry storage persistent (see ./config/config.yml for the path)
    #- ./registry/storage:/var/lib/registry:rw

proxy:
  container_name: proxy
  image: nginx
  restart: always
  links:
    - registry
  ports:
    - 5000:5000
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./passwords:/etc/nginx/password_folder/passwords
